### ISSUE TITLE
Lỗi - chức năng Dự trù hàng không lấy đúng số lượng đã xuất

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**ThangKT**_: `12` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng dự trù hàng không lấy đúng số lượng đã xuất!
---
khi lập dự trù rồi chọn xóa thì phần mềm không đánh dấu lại các chứng từ đã xóa đó
-> không lấy lại các thuốc đã xóa phiếu dự trù
---
```
Tổng xuất số lượng 529.694 
![image](https://user-images.githubusercontent.com/96155021/215384913-bca96bf0-d9c8-456d-880a-82b499245e50.png)
nhưng dự trù lấy lại số lượng đã xuất không đúng
![image](https://user-images.githubusercontent.com/96155021/215384995-d9c87478-07c2-4211-8c60-9d1efb15a2ca.png)

**Comment by nghivanbi** [comment]
Cập nhật:
https://github.com/dh-hos/dhg.hospitalmedicine/issues/12

**Comment by le-an-87** [comment]
Đã fix!
