### ISSUE TITLE
Yều cầu - chức năng dự trù thuốc bổ sung cấn trừ các phiếu xuất

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#12]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Chức năng dự trù hàng
 - Khi dự trù lấy số lượng từ các phiếu xuất phần mềm không có cấn trừ các toa trả lại của bệnh nhân nên dẫn đến số lượng dự trù nhiều hơn số lượng thực tế xuất cho bệnh nhân
 -> đề xuất cấn trừ các phiếu trả hoặc bổ sung chức năng cho bệnh viện tự chọn có cấn trừ hay không!

```
mahh ME165 xuất 40 trả 1
![image](https://user-images.githubusercontent.com/96155021/215404493-60567989-a365-4a1a-9f40-44abbda96924.png)

dự trù 40 
![image](https://user-images.githubusercontent.com/96155021/215404404-8c5d8f1d-5a98-4d4f-9922-bbecbc4bb08f.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3.23.0201.1](http://www.fsend.vn/download/ABkDlWmCtpC3jF_935o5lAvCg_GfMhiX)

**Comment by le-an-87** [comment]
Đã bổ sung!
