### ISSUE TITLE
Yều cầu - Bổ sung Biên bản kiểm nhập tự thiết kế.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalmedicine#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_022023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu ở thêm chức năng In biên bản kiểm nhập theo mẫu tự thiết kế đối với BV Nhi Đồng CT.
Hiện tại dữ liệu của BV không thấy chức năng tự thiết kế, dl mấy BV khác thì thấy được chức năng đó.
![image](https://user-images.githubusercontent.com/99630883/225806938-61d05946-8257-4ac3-8584-cf9c617842cf.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3.23.0321.1](http://www.fsend.vn/download/kSPN3EQ8m2y0qbSFLqzFOtyB3hiU3jHB)
