### ISSUE TITLE
Yều cầu - Bổ sung tham số loại bỏ số lượng âm trên BC sử dụng thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalmedicine#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiển tại trên mẫu báo cáo sử dụng thuốc bị thể hiện số âm, nguyên nhân là do trong tháng không có xuất thuốc cho tủ trực mà có sử dụng chức **nhập tủ trực điều về** dẫn đến cấn trừ bị âm. Cả Medicine và Secondsotre
Đề nghị bổ sung thêm tham số để loại trừ những mặt hàng bị âm như Anh Bi đã đề xuất.

![image](https://user-images.githubusercontent.com/99630883/229963583-3c7220d3-6eb4-45eb-ac1d-6421e53bac4b.png)
![image](https://user-images.githubusercontent.com/99630883/229963596-8a7d535b-fdb4-4305-af1c-3d656da02db1.png)

**Comment by nghivanbi** [comment]
Cập nhật Medicine: [v2.23.0407.1](http://www.fsend.vn/download/d1Z4nx1aOa_0Ul516vdUS22RWox1TORU)
