### ISSUE TITLE
Lỗi - Báo cáo sử dụng thuốc ghi nhận số lượng xuất tủ trực

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalmedicine#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYEN QUOC HOA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12_032023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `12` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `04` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Báo cáo sử dụng thuốc trên Medi ghi nhận:
1. Cộng số lượng xuất tủ trực vào cột "Khác": 
     - Trước đây đúng thì từ kho xuất cho tủ trực thì không lấy dữ liệu lên vì chưa xuất đi cho BN, khi nào xuất từ tủ trực xuất cho BN thì mới tính số lượng xuất => Đề nghị khi xuất từ KHO -> TỦ TRỰC thì **không hiển thị số lượng đó vào cột KHÁC**

2. Cộng số lượng tủ trực điều về vào cột "Nội trú": 
     -  Đề nghị khi nhập tủ trực điều về thì **không thể hiện số lượng vào cột NỘI TRÚ**, vì theo ý ở trên thì khi xuất từ KHO -> Tủ trực không thể hiện số liệu đó nên khi nhập từ Tủ trực điều về cũng không cần hiển thị. 
     
Test thực tế khi Xuất vào cột khác và Điều về vào cột Nội trú gây âm số lượng trên báo cáo sử dụng thuốc.

![image](https://user-images.githubusercontent.com/130281806/231111828-ed3a9847-f1c1-48e3-a3b0-3707d79ff5fd.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3,23,0418.1](http://www.fsend.vn/download/mUo0XmEH7K5caJrLJxS56o8Y--64mA3c)
