### ISSUE TITLE
Yều cầu - KHO NHÀ THUỐC > THỐNG KÊ XUẤT KHÁC > ĐƯA LÝ DO PHIẾU XUẤT KHÁC LÊN CỘT NỘI DUNG

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalmedicine#22]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `86066`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM BÁC SĨ BẮC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bsbac_042023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Khi sử dụng chức năng xuất khác của kho Nhà thuốc có ghi lý do xuất kho > Hiện tại thống kê Xuất kho > Xuất khác cột nội dung đang thể hiện nội dung chung.
Yêu cầu thể hiện lý do của phiếu xuất khác của kho Nhà thuốc lên cột nội dung trong thống kê Xuất khác để dễ quản lý > Lý do : dùng Chức năng Xuất khác để xuất cho nhiều mục đích khác nhau.

![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/a67c98b9-5653-417c-beb6-7cdf1e49f394)
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/95d2d488-688c-4303-88e5-ad6f65e9c294)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3.23.0526.1](http://www.fsend.vn/download/oQBn3y8Qt0XC5Fa74zwWW98W3BKW28eU)
