### ISSUE TITLE
Lỗi - BÁO CÁO NXT TỔNG HỢP THỐNG KÊ SAI SỐ LƯỢNG NHẬP HĐ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalmedicine#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN 12 **
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvq12_052023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `PU18` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thống kê báo cáo NXT tổng hợp bị đội số lượng nhập HĐ
Thẻ kho, tồn kho, NXT kho chẳn thể hiện đúng với phiếu nhập

![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/6e364abd-1349-40a2-a0f9-e29599b97c55)
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/7ff066d2-d2af-4afa-8716-7656b3d2caf8)
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/ff3e5cd0-7eb2-4fa4-806e-1e93b43425d0)

**Comment by nqhoa1005** [comment]
check vào tủ trực thì ra 394 còn bỏ ra nó đội lên 600 á anh
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/130281806/0f7b075b-2de0-4333-868a-c822c43ce4cd)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3.23.0606.1](http://www.fsend.vn/download/zZM3ZEUjxpNXemkb282rNkvxVNGyCYiD)
