### ISSUE TITLE
Lỗi - Báo cáo Nghiện, Hướng thần theo TT20/2017/TT-BYT

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalmedicine#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_cairang`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/pjN2u5arB

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
1. Medicine (kho 13) > Báo cáo tháng > Thuốc sử dụng > Sổ theo dõi khách hàng (Nhà thuốc) mua thuốc Nghiện/Hướng thần
   Khi tham số bcnghienht =2 (áp dụng theo TT20/2017/TT-BYT)

```
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/98437757/5c339bce-7307-46da-b874-fa061c66b774)

 In báo cáo Sổ theo dõi khách hàng load mẫu của TT19

![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/98437757/b634f81f-9d01-4620-a1cd-31227b5fc551)

![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/98437757/48a218f5-bbfa-45bd-b72a-fdadf5200f92)

Tiêu đề tab Mẫu 8 SAI so với Mẫu 7 trên bảng in

**Cập nhật mẫu PHỤ LỤC XXI theo TT20/2017/TT-BYT**

![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/98437757/156d250c-0d83-4a7b-aa82-8555d161b24a)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v3.23.0711.2](http://www.fsend.vn/download/yaz9hktv98SudPwBXkG5E8wf1aI9ya9E)
