### ISSUE TITLE
Lỗi - chức năng xuất trả nhà cung cấp

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_anthoi_20230629`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/GGORM7fwz)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng xuất trả nhà cung cấp.
 - Khi xuất trả nhà cung cấp phần mềm báo "Số phiếu này đã tồn tại"
 - > kiểm tra dữ liệu thì số phiếu không bị trùng.

* khi xuất kho có nhập ký hiệu Medicine sẽ thông báo và không cho lưu phiếu xuất
* Khi không nhập ký hiệu sẽ lưu được phiếu xuất.

```
Có nhập ký hiệu
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/9b0295b1-9c2d-43ee-ba27-3ff2d7a36c23)
Không nhập ký hiệu
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/cacb7c27-c57d-40e7-be8f-94473f92a12d)

**Comment by nghivanbi** [comment]
Cập nhật:
Medicine: [v2.23.06.29.1](http://www.fsend.vn/download/onwgNJgcxYRoz2Q6kwR98r0tyR15N72T)

**Comment by le-an-87** [comment]
đã fix!
