### ISSUE TITLE
Lỗi - Chức năng cập nhật xuất module Medicine và second không cập nhật được toa tủ trực nhà thuốc (BV Phụ Sản CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#38]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_tonkho_tutruc_22122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_tonkho_tutruc_22122023`](https://gofile.me/78TQg/TAnC9pkUQ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023112734` - _**MaKB**_: `2312013355` - _**MaBA**_: `022766` _**NgayKCB**_: `22/12/2023` - _**MaDV**_: `30` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**TuTruc**_: `NT6` - _**MaHH**_: `BO490` - _**SoHD**_: `PT8.X23.1222.084950` - _**NgayHD**_: `22/12/2023` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Treatment khi chỉ định toa thuốc tủ trực nhà thuốc ghi nhận dữ liệu toatutruc =2 (Giá trị diễn giải chỉ có 0 và 1)
Các module Medicine và second khi cập nhật lại tủ trực thì không tính được các toa có trường toatutruc = 2.
Chổ này anh xem lại thống nhất với module Treatment lại nhe anh. 
- BV đang bị vướng chổ này nếu kéo dài xuất thuốc đến khi cập nhật lại đúng thì có thể dẫn đến âm kho đó anh.
```
dữ liệu ghi nhận
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/bbfc6982-2381-4414-be78-38deafdf6f29)
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/29127655-638b-45e8-a146-9557f5fb31dc)
Medicine và second khi cập nhật không tính được các toa này
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/4b927d56-0327-4045-a68f-9f4aa0be2e46)

**Comment by nghivanbi** [comment]
toatutruc =2 là toa gì @vuongdh?

**Comment by vuongdh** [comment]
@nghivanbi để coi lại, rồi trả lời

**Comment by vuongdh** [comment]
toatutruc =2: Tủ trực nhà thuốc

**Comment by nghivanbi** [comment]
có mô tả không?

**Comment by vuongdh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/32563776/545ac0f2-5010-4487-be15-fa618bb7d28f)
Thấy trong code ghi nhận vậy.
Mô tả? --> không nhớ nữa, từ lúc làm tủ trực cho Phụ Sản tới giờ. Để kiếm lại xem

**Comment by nghivanbi** [comment]
Bản cũ nó lưu = 1 không hà, bản mới lưu = 2, tủ trức nhà thuốc bên đó sd lâu rồi mà.

**Comment by le-an-87** [comment]
chổ này coi giải quyết sớm giùm em anh @vuongdh , anh @nghivanbi ơi. cuối tháng cuối năm rồi bv cần cắt chuyển nữa nhe anh!
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/168c4f08-2ace-4e0e-ba29-2d1e18971b50)
