### ISSUE TITLE
Yêu cầu hỗ trợ Báo cáo NXT Tổng hợp có check Loại bỏ tủ trực

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalmedicine#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

PHẦN KHO DƯỢC 14
1. Báo cáo NXT Tổng hợp có check loại bỏ tủ trực
2. Biên bản kiểm kê, Biên bản kiểm nhập hỗ trợ ghép thêm tên hoạt chất sau tên hàng hóa.
3. Thẻ kho: hỗ trợ ghép tên hoạt chất khi xem và in thẻ kho
4. Xuất khoa phòng hỗ trợ đưa vào phần mẫu báo cáo sử dụng Thuốc, Hóa chất, VTYT (TT22)

```

**Comment by nghivanbi** [comment]
Đã hỗ trợ
