### ISSUE TITLE
Lỗi - BC Xuất nhập tồn và xuất nhập tồn tổng hợp (BV Thốt Nốt)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_nxt_122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_nxt_122023`](https://gofile.me/78TQg/zfSB8GSRD)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc%20XNT%20TH-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**MaHH**_: `K506` - _**SoHD**_: `D70.00010/12` - _**NgayHD**_: `29/12/2023` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc%20XNT-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `15` - _**MaHH**_: `K506` - _**SoHD**_: `D70.00010/12` - _**NgayHD**_: `29/12/2023` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Hiện tại bệnh viện có 2 kho chẳn: kho 14 và kho 15 thuộc khoa dược
1. BC Xuất nhập tồn tổng hợp tính sai số lượng khi chọn kho
   Kiểm tra kho chẳn 14 Mã thuốc: K506
   - khi lấy báo cáo Tồn kho TH chọn kho 14 có  tồn cuối = 0
   -> Báo cáo XNT TH chọn kho 14 có tồn cuối = 768
   => báo cáo không tính được chứng từ xuất điều chuyển nội bộ.

2. BC Xuất nhập tồn tính sai số lượng khi có chứng từ nhập điều chuyển nội bộ
 Kiểm tra kho chẳn 15 Mã thuốc: K506
- BC tồn kho 15 có tồn cuối = 339
- BC XNT kho 15 có tồn cuối = -429
   => báo cáo không tính được chứng từ nhập điều chuyển nội bộ.
```
- Chứng từ điều chuyển nội bộ
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/e12ea9d5-b3bc-4f02-bd17-c9e1c17f4182)

1. BC XNT TH kho 14
- tồn kho TH
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/60662601-08ee-4025-8a7c-f6139eff5682)
- XNT TH
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/fe789a18-604c-46fd-8ca1-bf54d086dde7)

2. BC XNT kho 15
- BC Tồn kho
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/79066aed-a293-4e2e-a93c-cf2795109d74)
- BC XNT
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/11d1d50e-a858-4960-aa85-08e2bf3e4d4e)

**Comment by nghivanbi** [comment]
Ok đã hiểu lỗi, kiểm tra dữ liệu để fix nhé.
