### ISSUE TITLE
Lỗi - Cập nhật hàng thầu (BV Thốt Nốt)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalmedicine#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_hangthau_14062024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_hangthau_14062024`](https://gofile.me/78TQg/kozjXkmKX)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**MaHH**_: `R181` - _**GoiThau**_: `QĐ2199` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng cập nhật hàng thầu.
Khi bổ sung thêm thuốc vào gói thầu phần mềm báo lỗi trùng dữ liệu

```
![ảnh](https://github.com/dh-hos/dhg.hospitalmedicine/assets/96155021/116b6c11-03a8-4867-8751-2ee16e7f590e)

**Comment by ongtrieuhau-dh** [comment]
**Cập nhật script để hỗ trợ lỗi này**
![image](https://github.com/dh-hos/dhg.hospitalmedicine/assets/155862740/e6b2c39d-cfc2-4a56-a5d5-7a13b3c75aef)
