### ISSUE TITLE
Yều cầu - Báo cáo NXT thêm cột

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalmedicine#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da Liễu ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dalieudt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu mẫu báo cáo nhập xuất tồn(TAB 1) của **Kho Nhà thuốc** có thêm 3 cột: Giá xuất, tiền lãi và tiền lỗ. Tiêu chí tính toán giống như báo cáo lãi lỗ hiện có trong menu **Báo cáo tháng/Báo cáo lãi lỗ.**

![image](https://user-images.githubusercontent.com/99630883/200207754-72fc9b54-9c20-4a9b-9552-0f06b96c1924.png)
![image](https://user-images.githubusercontent.com/99630883/200207786-2b205f49-d94b-4248-9b30-1b82ee25e3fe.png)

**Comment by nghivanbi** [comment]
Đã hỗ trợ cập nhật Med v3.23.0104.1

**Comment by hvtuan1987** [comment]
ok anh !
